
/*
const asyncHandler = (fn) => {
  (req,res,next)=>{
    Promise.resolve(fn(req,res,next))
    .catch(err=>next(err));
  }
}

*/


// const asyncHandler = () => {}
// const asyncHandler = (func) => () => {}
// const asyncHandler = (func) => async () => {}


const asyncHandler=(fn)=> async(req,res,next) => {
  try {
    await fn(req,res,next);
  } catch (error) {
    res.status(error.code || 500).json({
      success:false,
      message:error.message
    })
  }
}

export default asyncHandler;